"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { formatDistanceToNow } from "date-fns";
import {
  AlertCircle,
  CheckCircle2,
  Clock,
  ExternalLink,
  GitBranch,
  GitPullRequest,
  Loader2,
  Sparkles,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { statusBadge } from "@/features/dashboard/lib/status-style";
import { ReviewModal } from "./review-modal";
import { DASHBOARD_ROUTES } from "@/features/dashboard/lib/routes";

type PullRequestItem = {
  id: string;
  repoFullName: string;
  prNumber: number;
  title: string;
  authorLogin: string | null;
  baseBranch: string;
  status: string;
  reviewComment: string | null;
  reviewedAt: string | null;
  createdAt: string;
};

type OverviewPrListProps = {
  pullRequests: PullRequestItem[];
};

export function OverviewPrList({ pullRequests }: OverviewPrListProps) {
  const [filter, setFilter] = useState<"all" | "reviewed" | "processing">("all");
  const [selectedPr, setSelectedPr] = useState<PullRequestItem | null>(null);

  const filteredPrs = useMemo(() => {
    if (filter === "all") return pullRequests;
    if (filter === "reviewed") return pullRequests.filter((pr) => pr.status === "reviewed");
    if (filter === "processing")
      return pullRequests.filter((pr) => pr.status === "processing" || pr.status === "pending");
    return pullRequests;
  }, [pullRequests, filter]);

  return (
    <>
      <Card className="border-border/80 shadow-xs">
        <CardHeader className="p-5 pb-3">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <CardTitle className="text-base font-semibold flex items-center gap-2">
                <GitPullRequest className="size-4 text-primary" />
                Recent Pull Request Reviews
              </CardTitle>
              <CardDescription className="text-xs">
                Automated code reviews generated by ReviewBit on your GitHub PRs.
              </CardDescription>
            </div>
            {pullRequests.length > 0 && (
              <div className="flex items-center gap-1.5 self-start sm:self-auto">
                <Button
                  size="sm"
                  variant={filter === "all" ? "secondary" : "ghost"}
                  onClick={() => setFilter("all")}
                  className="h-7 text-xs px-2.5"
                >
                  All ({pullRequests.length})
                </Button>
                <Button
                  size="sm"
                  variant={filter === "reviewed" ? "secondary" : "ghost"}
                  onClick={() => setFilter("reviewed")}
                  className="h-7 text-xs px-2.5"
                >
                  Reviewed ({pullRequests.filter((pr) => pr.status === "reviewed").length})
                </Button>
                <Button
                  size="sm"
                  variant={filter === "processing" ? "secondary" : "ghost"}
                  onClick={() => setFilter("processing")}
                  className="h-7 text-xs px-2.5"
                >
                  In Flight (
                  {
                    pullRequests.filter(
                      (pr) => pr.status === "processing" || pr.status === "pending"
                    ).length
                  }
                  )
                </Button>
              </div>
            )}
          </div>
        </CardHeader>

        <CardContent className="p-5 pt-2">
          {pullRequests.length === 0 ? (
            <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-border py-12 px-6 text-center">
              <div className="flex size-12 items-center justify-center rounded-2xl bg-muted text-muted-foreground mb-3">
                <GitPullRequest className="size-6" />
              </div>
              <h3 className="font-semibold text-sm text-foreground">
                No pull requests reviewed yet
              </h3>
              <p className="text-xs text-muted-foreground max-w-md mt-1 mb-4 leading-relaxed">
                When you open or synchronize a PR on any repository connected to ReviewBit, our AI
                engine will automatically break down the diff, evaluate the code, and post comprehensive feedback.
              </p>
              <div className="flex items-center gap-3">
                <Button size="sm" asChild variant="outline">
                  <Link href={DASHBOARD_ROUTES.repos}>Check Repositories</Link>
                </Button>
                <Button size="sm" asChild>
                  <Link href={DASHBOARD_ROUTES.github}>GitHub Settings</Link>
                </Button>
              </div>
            </div>
          ) : filteredPrs.length === 0 ? (
            <div className="py-8 text-center text-xs text-muted-foreground">
              No pull requests matching &quot;{filter}&quot; filter.
            </div>
          ) : (
            <div className="divide-y divide-border/60">
              {filteredPrs.map((pr) => {
                const isReviewed = pr.status === "reviewed";
                const isProcessing = pr.status === "processing";
                const isPending = pr.status === "pending";
                const isRateLimited = pr.status === "rate_limited";

                const githubPrUrl = `https://github.com/${pr.repoFullName}/pull/${pr.prNumber}`;

                return (
                  <div
                    key={pr.id}
                    className="flex flex-col gap-3 py-3.5 first:pt-1 last:pb-1 sm:flex-row sm:items-center sm:justify-between transition-colors hover:bg-muted/30 -mx-2 px-2 rounded-lg"
                  >
                    <div className="space-y-1 min-w-0 flex-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-mono text-xs font-semibold text-primary">
                          #{pr.prNumber}
                        </span>
                        <a
                          href={githubPrUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="font-medium text-xs sm:text-sm text-foreground hover:underline truncate max-w-[280px] sm:max-w-md"
                          title={pr.title}
                        >
                          {pr.title}
                        </a>
                      </div>

                      <div className="flex items-center gap-2 text-[11px] text-muted-foreground flex-wrap">
                        <span className="font-medium text-foreground/80">{pr.repoFullName}</span>
                        <span>•</span>
                        <span className="inline-flex items-center gap-1">
                          <GitBranch className="size-3" />
                          {pr.baseBranch}
                        </span>
                        {pr.authorLogin && (
                          <>
                            <span>•</span>
                            <span>@{pr.authorLogin}</span>
                          </>
                        )}
                        <span>•</span>
                        <span>
                          {formatDistanceToNow(new Date(pr.createdAt), { addSuffix: true })}
                        </span>
                      </div>
                    </div>

                    <div className="flex items-center gap-2.5 shrink-0 self-start sm:self-center">
                      {isReviewed && (
                        <span className={statusBadge("success", "gap-1 text-[11px]")}>
                          <CheckCircle2 className="size-3" />
                          Reviewed
                        </span>
                      )}
                      {isProcessing && (
                        <span className={statusBadge("warning", "gap-1 text-[11px]")}>
                          <Loader2 className="size-3 animate-spin" />
                          Reviewing
                        </span>
                      )}
                      {isPending && (
                        <span className={statusBadge("neutral", "gap-1 text-[11px]")}>
                          <Clock className="size-3" />
                          Queued
                        </span>
                      )}
                      {isRateLimited && (
                        <span className={statusBadge("danger", "gap-1 text-[11px]")}>
                          <AlertCircle className="size-3" />
                          Limit Reached
                        </span>
                      )}

                      {pr.reviewComment ? (
                        <Button
                          size="sm"
                          variant="secondary"
                          onClick={() => setSelectedPr(pr)}
                          className="h-7 text-xs gap-1.5"
                        >
                          <Sparkles className="size-3 text-primary" />
                          View Review
                        </Button>
                      ) : (
                        <Button size="sm" variant="ghost" asChild className="h-7 text-xs">
                          <a href={githubPrUrl} target="_blank" rel="noopener noreferrer">
                            <ExternalLink className="size-3" />
                          </a>
                        </Button>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>

      <ReviewModal
        isOpen={Boolean(selectedPr)}
        onClose={() => setSelectedPr(null)}
        pr={selectedPr}
      />
    </>
  );
}
